stages:
  - build
  - deploy

variables:
  BATCH_BUILD: "1"
  V: "0"
  MAKEFLAGS: "-j5 --no-keep-going"
  # IDF_PATH: "$CI_PROJECT_DIR/esp-idf"
  IDF_CI_BUILD: "1"

before_script:
  # add gitlab ssh key
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo -n $GITLAB_KEY > ~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git --version
  - git submodule update --init --recursive
  # - git clone --recursive --branch release/v4.2 --depth 1 $GITLAB_SSH_SERVER/espressif/esp-idf.git
  # - export PATH="$IDF_PATH/tools:$PATH"
  # - cd esp-idf
  # - source tools/ci/setup_python.sh
  # - source tools/ci/configure_ci_environment.sh
  # - tools/idf_tools.py --non-interactive install && eval "$(tools/idf_tools.py --non-interactive export)" || exit 1
  # - cd ..

.build_examples_template: &build_examples_template
  stage: build
  image: espressif/idf:release-v4.2
  tags:
    - build
  # Artifacts are not used temporarily
  # artifacts:
  #   when: always
  #   paths:
  #     - $LOG_PATH
  #   expire_in: 1 week
  # variables:
  #   LOG_PATH: "$CI_PROJECT_DIR/log_examples"

# build_demo_make:
#   <<: *build_examples_template
#   script:
#     - cd esp32-s2-kaluga-1
#     - cd examples/camera
#     - make defconfig && make -j5
#     - cd ../../
#     - cd examples/lcd
#     - make defconfig && make -j5
#     - cd ../../
#     - cd examples/touch
#     - make defconfig && make -j5
#     - cd ../../

build_kaluga_demo_cmake:
  <<: *build_examples_template
  script:
    - cd esp32-s2-kaluga-1
    - cd examples/camera
    - idf.py fullclean
    - idf.py set-target esp32s2 
    - idf.py build
    - cd ../../
    - cd examples/lcd
    - idf.py fullclean
    - idf.py set-target esp32s2 
    - idf.py build
    - cd ../../
    - cd examples/touch
    - idf.py fullclean
    - idf.py set-target esp32s2 
    - idf.py build
    - cd ../../
    - cd examples/adc_button
    - idf.py fullclean
    - idf.py set-target esp32s2 
    - idf.py build
    - cd ../../
    - cd examples/touch_audio
    - idf.py fullclean
    - idf.py set-target esp32s2 
    - idf.py build
    - cd ../../
    - cd examples/web_tts
    - idf.py fullclean
    - idf.py set-target esp32s2 
    - idf.py build

build_hmi_demo_cmake:
  <<: *build_examples_template
  image: espressif/idf:latest
  script:
    - cd esp32-s2-hmi-devkit-1
    - cd examples/audio/audio_record
    - idf.py fullclean
    - idf.py set-target esp32s2
    - idf.py build
    - cd ../../../
    - cd examples/audio/music_player
    - idf.py fullclean
    - idf.py set-target esp32s2
    - idf.py build
    - cd ../../../
    - cd examples/get-started/hello_world
    - idf.py fullclean
    - idf.py set-target esp32s2
    - idf.py build
    - cd ../../../
    - cd examples/get-started/led_blink
    - idf.py fullclean
    - idf.py set-target esp32s2
    - idf.py build
    - cd ../../../
    - cd examples/get-started/provision
    - idf.py fullclean
    - idf.py set-target esp32s2
    - idf.py build
    - cd ../../../
    - cd examples/sensors
    - idf.py fullclean
    - idf.py set-target esp32s2
    - idf.py build
    - cd ../../
    - cd examples/storage/sdcard_fatfs
    - idf.py fullclean
    - idf.py set-target esp32s2
    - idf.py build
    - cd ../../../
    - cd examples/ulp
    - idf.py fullclean
    - idf.py set-target esp32s2
    - idf.py build
    - cd ../../
    - cd examples/usb/usb_dfu_cdc
    - idf.py fullclean
    - idf.py set-target esp32s2
    - idf.py build
    - cd ../../../
    - cd examples/usb/usb_msc
    - idf.py fullclean
    - idf.py set-target esp32s2
    - idf.py build
    - cd ../../../

push_master_to_github:
  stage: deploy
  only:
    - master
    - /^release\/v/
#  when: on_success
  image: $CI_DOCKER_REGISTRY/esp32-ci-env
  variables:
    GIT_STRATEGY: clone
    GITHUB_PUSH_REFS: refs/remotes/origin/release refs/remotes/origin/master
  before_script:
    - echo "skip default before_script"
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GH_PUSH_KEY >> ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - git remote add github git@github.com:espressif/esp-dev-kits.git
    # What the next line of script does: goes through the list of refs for all branches we push to github,
    # generates a snippet of shell which is evaluated. The snippet checks CI_BUILD_REF against the SHA
    # (aka objectname) at tip of each branch, and if any SHAs match then it checks out the local branch
    # and then pushes that ref to a corresponding github branch
    #
    # NB: In gitlab 9.x, CI_BUILD_REF was deprecated. New name is CI_COMMIT_REF. If below command suddenly
    # generates bash syntax errors, this is probably why.
    - eval $(git for-each-ref --shell bash --format 'if [ $CI_BUILD_REF == %(objectname) ]; then git checkout -B %(refname:strip=3); git push --follow-tags github %(refname:strip=3); fi;' $GITHUB_PUSH_REFS)
  
  